# Site settings
title: "Tower of Hanoi"
email: toh@necst.it
description: "CTFs write-ups by the PoliMi Security Team."
baseurl: ""
url: "http://toh.necst.it"
title_description: "Badass students doing things on their PCs? Check. Soulless coding monkeys solving security challenges? Check. Handsome Italian guys better than Gordon Ramsey? Check. Perfectly and lovely written write-ups? Check. Sounds perfect."
#google_analytics: ""
title_image: "/img/logo.png"
disqus_account: towerofhanoi
github_repository: https://github.com/towerofhanoi
post_limit: 5
more: "read the full article"
# Social usernames/URLs
twitter_username: towerofhanoi
github_username: towerofhanoi
#linkedin_link: 
#google_plus_link: 
#stackoverflow_link: 

gems:
  - jekyll-sitemap

# Footer
footer_left: "Theme 'Carte Noire' by Jacob Tomlinson"
footer_right: "Customized by the Tower of Hanoi team."

excerpt_separator: "\n\n\n\n"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# Build settings
permalink: /:categories/:title/
exclude: [vendor]
defaults: [{scope: {path: ""}, values: {layout: "post"}}]
