# Site settings
title: "Tower of Hanoi"
email: info@changeme.me
description: "CTFs write-ups by the PoliMi Security Team."
baseurl: ""
url: "http://towerofhanoi.github.io/"
title_description: "Badass students doing things on their PCs? Check. Soulless coding monkeys solving security challenges? Check. Handsome Italian guys better than Gordon Ramsey? Check. Perfectly and lovely written write-ups? Check. Sounds perfect."
title_image: "http://polictf.it/images/logo.png"
#google_analytics: ""
#disqus_account: cartenoire
github_repository: https://github.com/towerofhanoi
#addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: towerofhanoi
github_username: towerofhanoi
#linkedin_link: 
#google_plus_link: 
#stackoverflow_link: 

# Footer
footer_left: "Theme 'Carte Noire' by Jacob Tomlinson"
#footer_right: ""
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
defaults: [{scope: {path: ""}, values: {layout: "post"}}]
